### ISSUE TITLE
Support from someone deeply familiar with Go?

### ISSUE THREAD

**Issue by romainfrancois** [rstats-go/proposal#2]

**Comment by glycerine** [comment]
I'll offer what assistance I can. I did recently write https://github.com/gijit/gi, which is an interpreter for most of the Go language.

**Comment by romainfrancois** [comment]
Thanks @glycerine

**Comment by kortschak** [comment]
I have this implemented [here](https://github.com/rgonomic/rgo) now.

**Comment by romainfrancois** [comment]
Great. I'll close this issue now then :-)
