### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by krlmlr** [rstats-go/proposal#7]
The proposal mentions that we'll be posting info through a dedicated webpage. Why not create a simple landing page now, like https://r-dbi.org/? We could copy your blog post there, and also add an article with the more technical parts of the proposal, to which we can then refer from the proposal.

**Comment by krlmlr** [comment]
Let's postpone this for now.

**Comment by romainfrancois** [comment]
I started this at some point using the https://github.com/rbind/rgo repo and the go.rbind.io domain

If you think that helps, we could revisit with a more appropriate Hugo theme.

**Comment by romainfrancois** [comment]
Updated https://go.rbind.io
